import type { Metadata } from 'next'
import './globals.css'
import { nunito, quando } from './fonts'
import { ClerkProvider } from '@clerk/nextjs'
import Head from 'next/head'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <title>PaisaBachat</title>
          <meta property="og:title" content="Paisa Bachat" key="title" />
        </Head>
        <body className={quando.className}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
